export const theme = {
  font: {
    primary: "'Work Sans', sans-serif",
    secondary: "'Rubik', sans-serif",
  },
  colors: {
    white: '#FFFFFF',
    blueGray10: '#F4F8FA',
    blueGray50: '#E9EEF2',
    blueGray100: '#CBD5DC',
    blueGray300: '#8A9CA9',
    blueGray400: '#708797',
    blueGray600: '#708797',
    blueGray900: '#1E2A32',
    brandColorPrimary: '#1B31A8',
    brandColorSecondary: '#0079FF',
  },
  gutterSpace: {
    xSmall: '4px',
    small: '8px',
    medium: '16px',
    xMedium: '20px',
    xxMedium: '24px',
    large: '32px',
    xLarge: '40px',
    xxLarge: '48px',
    xxxLarge: '56px',
  },
  fontSizes: {
    xxSmall: '1rem',
    xSmall: '1.2rem',
    small: '1.4rem',
    medium: '1.6rem',
    xMedium: '1.8rem',
    large: '2rem',
    xLarge: '2.4rem',
    xxLarge: '3.2rem',
  },
  breakpoints: {
    mobile: 600,
  },
  borderRadius: {
    small: '4px',
    medium: '8px',
    large: '32px',
  },
};
